delimiter $$

CREATE TABLE SW_ACTIVITY (
  PROJECT_ID varchar(10) NOT NULL AUTO_INCREMENT,
  ACTIVITY_ID varchar(10) NOT NULL,
  STATUS varchar(1) DEFAULT NULL,
  DESCR varchar(45) DEFAULT NULL,
  BEGIN_DT datetime DEFAULT NULL,
  END_DT datetime DEFAULT NULL,
  MANAGER varchar(10) DEFAULT NULL,
  TEAM_ID varchar(10) DEFAULT NULL,
  PRIMARY KEY (PROJECT_ID,ACTIVITY_ID),
) ENGINE=MyISAM

--
-- KEY SW_ACTIVITY_SW_PROJECT_IDX (PROJECT_ID),
--  KEY SW_ACTIVITY_SW_EMPLOYEES_IDX (MANAGER),
--  KEY SW_ACTIVITY_SW_TEAM_IDX (TEAM_ID)